### ISSUE TITLE
Couldn't add from gradle

### ISSUE THREAD

**Issue by cemtufekci** [RHSaliya/PasswordStrengthView#1]
Hi, project couldn't be found when user tries to add it from gradle

"Could not find com.github.RHSaliya:PasswordStrengthView:1.1"

**Comment by RHSaliya** [comment]
hello, checking for the issue.

**Comment by RHSaliya** [comment]
Try: 	        implementation 'com.github.RHSaliya:PasswordStrengthView:1.5'
